openapi: 3.0.0
components:
  schemas:
    Error404Response:
      properties:
        message:
          type: string
    ErrorResponse:
      properties:
        message:
          type: string
    PostVehiculoRequest:
      properties:
        capacidad_cargo:
          type: string
        consumibles:
          type: string
        costo_en_creditos:
          type: string
        tripulacion:
          type: string
        largo:
          type: string
        fabricante:
          type: string
        valocidad_atmosferica_maxima:
          type: string
        modelo:
          type: string
        nombre:
          type: string
        pasajeros:
          type: string
        pilotos:
          type: array
          items:
            type: string
        peliculas:
          type: array
          items:
            type: string
        url:
          type: string
        clase_de_vehiculo:
          type: string
        creado:
          type: string
        editado:
          type: string
    VehiculoResponse:
      properties:
        ID:
          type: string
        capacidad_cargo:
          type: string
        consumibles:
          type: string
        costo_en_creditos:
          type: string
        tripulacion:
          type: string
        largo:
          type: string
        fabricante:
          type: string
        valocidad_atmosferica_maxima:
          type: string
        modelo:
          type: string
        nombre:
          type: string
        pasajeros:
          type: string
        pilotos:
          type: array
          items:
            type: string
        peliculas:
          type: array
          items:
            type: string
        url:
          type: string
        clase_de_vehiculo:
          type: string
        creado:
          type: string
        editado:
          type: string
  securitySchemes: {}
info:
  title: Serverles Api - aws - swapi
  description: >-
    Esta api se ha desarrollado para obtener un modelo de vehiculo y para
    guardar un modelo vehiculo
  version: 1.0.0
paths: {}
