service: aws-test-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-2
  stage: dev
  profile: default

plugins:
  - serverless-offline
  - serverless-dynamodb-local
  - serverless-openapi-documentation

functions:
  crearVehiculo:
    handler: src/handler.crearVehiculo
    events:
      - httpApi:
          path: /vehiculo
          method: post
  obtenerVehiculo:
    handler: src/handler.obtenerVehiculo
    events:
      - httpApi:
          path: /vehiculo/{id}
          method: get

custom:
  tableName: vehiculosTable
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true
    migration:
      dir: offline/migrations
  # documentation: ${file(serverless.doc.yml):documentation}

resources:
  Resources:
    vehiculosTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: vehiculosTable
        AttributeDefinitions:
          - AttributeName: ID
            AttributeType: S
        KeySchema:
          - AttributeName: ID
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
