service: aws-test-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: ${env:AWS_REGION, 'us-east-2'}
  profile: ${env:AWS_PROFILE, 'default'}

plugins:
  - serverless-dotenv-plugin
  - serverless-offline
  - serverless-dynamodb-local
  - serverless-openapi-documentation

functions:
  crearVehiculo:
    handler: src/handler.crearVehiculo
    events:
      - httpApi:
          path: /vehiculo
          method: post
          documentation: ${file(serverless.doc.yml):endpoints.crearVehiculo}
          
  obtenerVehiculo:
    handler: src/handler.obtenerVehiculo
    events:
      - httpApi:
          path: /vehiculo/{id}
          method: get
          documentation: ${file(serverless.doc.yml):endpoints.obtenerVehiculo}

custom:
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true
    migration:
      dir: offline/migrations
  documentation: ${file(serverless.doc.yml):documentation}

resources:
  Resources:
    DynamoDBTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TableName: vehiculosTable
        AttributeDefinitions:
          - AttributeName: ID
            AttributeType: S
        KeySchema:
          - AttributeName: ID
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
